### ISSUE TITLE
Automatically map R objects to TF.Learn column variables

### ISSUE THREAD

**Issue by kevinushey** [rstudio/tflearn#1]
When building a model with TF.Learn, one must generate 'column's from the input data, typically defining the 'type' or 'shape' of data expected in a particular column. For example, the example in https://www.tensorflow.org/tutorials/tflearn/ has:

```
# Specify that all features have real-value data
feature_columns = [tf.contrib.layers.real_valued_column("", dimension=4)]
```

indicating that the feature-columns input is an array with a single real valued column of dimension 4 (if I am understanding the API correctly). Other columns are described at https://www.tensorflow.org/tutorials/linear/overview.

We likely want to be able to construct this `feature_columns` object based on R inputs automatically. For example:

| R | TF.Learn |
| - | - |
| numeric | `real_valued_column` |
| integer | coerce to numeric + `real_valued_column` (?) |
| factor | `sparse_column_with_keys` |
| string | `sparse_column_with_hash_bucket` |

We may also want to make the transformations applied here user-configurable, e.g. with something like:

```
feature.transformations <- list(
    Petal.Length = function(x) {
        # transform the 'Petal.Length' column before passing to TF.Learn
    })
)
```

We might also want to just avoid making this part of the interface, and ask the user to explicitly transform the data before calling into the `tflearn` APIs -- I'm not yet sure what is most appropriate.

@terrytangyuan, does this sound like the right approach to you?

**Comment by jjallaire** [comment]
We'll want the feature transformations to be done within tensorflow if possible (since this will bring a significant performance advantage in the distributed / large dataset cases). I think that this is orthogonal to whether automatic transformations are applied. I think taking a data frame and doing something reasonable with it *sounds like* a good idea, however if the nature of programming for TF (and in using the new modeling recipes) is that you explicitly define your features then it would be okay to also make it explicit here.

@terrytangyuan You probably have a better idea than we do on this. I know that TFLearn includes some pandas integration -- is that similar to what Kevin is proposing here w/ creating automatic feature transformations imputed from the structure of the dataset?

**Comment by terrytangyuan** [comment]
I think users can do whatever they want and then TF.Learn can treat that as raw data (though it's feature engineered). We can provide some default conversions but they defeats the purpose of this extensible module. A lot of the design decisions in TF.Learn were proven to be well-suited for deep learning applications. 

If you take a look at this [input_fn example](https://github.com/rstudio/tflearn/blob/master/inst/examples/boston_input_fn.R) I added, you'll see users can not only perform transformations outside of TFLearn but also be able to use TFLearn feature column transformations to further enhance and combine the features in some way (I haven't tested an example yet but will soon). 

IMO, I think we should get away from pandas when possible since R' data.table, dplyr, etc., can provide much more functionalities that R users are familiar with. It's more for Python users to have an easier transition to use TFLearn.

**Comment by terrytangyuan** [comment]
@kevinushey Re: your table of conversion, I think it might be a good idea potentially going forward but for now let's leave those to users and we'll see a trend or need for that in the future. IMO, I think we need to be 100% sure when we are doing any sort of automatic conversion.

**Comment by terrytangyuan** [comment]
Perhaps we can make a `default_input_fn()` that does that automatic conversion for users for now. The examples you gave in the table are pretty much true. Users can decide whether to use the conversion.

**Comment by kevinushey** [comment]
Perhaps I'm misunderstanding what's necessary here, as well. Based on your example in https://github.com/rstudio/tflearn/blob/master/inst/examples/boston_input_fn.R, it seems like using `tf$constant` when specifying inputs to a model is sufficient. Is that correct? When exactly do `real_valued_column` and friends come into play?

**Comment by terrytangyuan** [comment]
Sorry for the confusion. Perhaps [this wide-and-deep tutorial](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/learn/wide_n_deep_tutorial.py) may demonstrate better. Think about `input_fn` being used as input handling, e.g. converting `data.frame` and `data.table` to `Tensors`. Then use FeatureColumn module to construct Features that can be used for estimator construction, e.g. `DNNLinearCombinedClassifier ` accepts two sets of columns - `linear_feature_columns` and  `dnn_feature_columns`. 

It's more like a separation of responsibility - data cleaning vs. feature engineering. 

Hope this is helpful.

**Comment by kevinushey** [comment]
Thanks! Okay, I think I understand now. Where an R user might define transformations inline using the formula interface, e.g.

    lm(y ~ X + X^2 + X^3, data = data)

the TF.Learn user would instead define those transformations within `input_fn`. When no transformation of variables is necessary (ie -- we're just using input data as-is), then a plain `tf$constant` is sufficient. Does that sound correct?

**Comment by terrytangyuan** [comment]
Exactly. Great!

**Comment by jjallaire** [comment]
I'd like to echo the bias against too much automatic binding too early. It seems like TF users do quite a bit of feature engineering to get models to perform in an optimal fashion, and while we can create a nice looking "hello, world" example w/ automagic mapping of e.g. the `iris` dataset, this doesn't reflect real world scenarios.

So I think we should always assume that features will be manually specified and only later (and then only if necessary) do the data frame binding. I think this dovetails with where @topepo and @hadley are going with recipes -- the input to a model is a model matrix rather than a data frame.

**Comment by kevinushey** [comment]
I think everything here is now handled by the recipe-driven approach -- see e.g.

https://github.com/rstudio/tflearn/blob/master/R/tf_linear_regression.R

I think this is a step in the right direction; hopefully we can further refine the interface from here!
